# next-swarm.ps1 - Phase 5 -> Phase 6 Transition
# Generated by Claude-4 (Polish/Review)
#
# Phase 5 Final State:
#   - Backend: 214 tests passing (22 test files)
#   - Frontend: 173 tests passing (7 test files)
#   - Total: 387 tests, zero failures
#   - Production build: 428KB JS + 33KB CSS + 179KB highlight.js
#   - Docker: Dockerfile (multi-stage) + docker-compose.yml
#   - Env config: .env support for all runtime settings
#   - Backup: GET /api/backup endpoint for SQLite dump
#   - Templates: Full CRUD + frontend selector dropdown
#   - Sparkline: Task completion trend graph in Dashboard
#   - Accessibility: 41 a11y tests, ARIA roles, keyboard navigation
#   - Process reconciliation: Detects/reattaches running subprocesses
#   - Subprocess fix: Popen + daemon threads (Windows SelectorEventLoop compat)
#
# Phase 6 Focus: Search, Analytics, Monitoring, Documentation

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Phase 5 Complete -> Launching Phase 6" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Phase 5: Docker, Templates, Advanced Features - DONE" -ForegroundColor Green
Write-Host "  387 tests passing (214 backend + 173 frontend)" -ForegroundColor Green
Write-Host "  Production build: 428KB JS + 33KB CSS" -ForegroundColor Green
Write-Host ""
Write-Host "  Phase 6: Search, Analytics, Monitoring, Docs" -ForegroundColor Yellow
Write-Host ""

# Generate Phase 6 task board
$phase6Tasks = @"
# Latent Underground - Task Board (Phase 6)

## Claude-1 [Backend/Core] - Search, analytics, and monitoring APIs

- [ ] Add project search/filter endpoint: GET /api/projects?search=&status=&sort= with query params
- [ ] Add analytics endpoints: GET /api/projects/{id}/analytics (run trends, agent efficiency, phase durations)
- [ ] Add centralized log endpoint: GET /api/logs/search?q=&level=&agent=&from=&to= with full-text search
- [ ] Add health check endpoint: GET /api/health (db status, active processes, uptime, version)
- [ ] Add OpenAPI/Swagger docs: enable FastAPI auto-docs at /docs with proper descriptions
- [ ] Signal: Create .claude/signals/backend-ready.signal

## Claude-2 [Frontend/Interface] - Search UI, analytics dashboard, log improvements

- [ ] Add project search bar + status filter in Sidebar (instant filter as you type)
- [ ] Add analytics tab in ProjectView: run trend chart, agent efficiency bars, phase timeline
- [ ] Add log search: text search input, log level filter, timestamp range picker, copy/download
- [ ] Add browser notifications: Web Push API for swarm completion/failure events
- [ ] Add health status indicator in header (green/yellow/red dot showing backend connectivity)
- [ ] Signal: Create .claude/signals/frontend-ready.signal

## Claude-3 [Integration/Testing] - Test coverage for new features

- [ ] Add tests for project search/filter API (search term, status filter, sort, pagination)
- [ ] Add tests for analytics endpoint (run trends, empty data, multi-run aggregation)
- [ ] Add tests for centralized log search (text search, level filter, date range)
- [ ] Add tests for health check endpoint (db up, db down, process counting)
- [ ] Add frontend tests for search UI, analytics components, log search, notifications
- [ ] Signal: Create .claude/signals/tests-passing.signal

## Claude-4 [Polish/Review] - Final quality gate

- [ ] Review all Phase 6 code changes for quality and consistency
- [ ] Verify no regressions: all Phase 5 tests still pass (387+)
- [ ] Performance review: search queries use indexes, analytics queries are efficient
- [ ] Documentation review: API docs accurate, README updated with new features
- [ ] FINAL: Generate next-swarm.ps1 for Phase 7 (if needed) or mark project complete

## Completion Criteria
- [ ] Projects searchable and filterable by name/status
- [ ] Analytics dashboard shows run trends and agent efficiency
- [ ] Logs searchable with text, level, and date filters
- [ ] Health endpoint provides system status at a glance
- [ ] All tests pass (backend + frontend, including new Phase 6 tests)
"@

$phase6Tasks | Out-File -FilePath "tasks/TASKS.md" -Encoding UTF8
Write-Host "  Generated new tasks/TASKS.md for Phase 6" -ForegroundColor Green
Write-Host ""

# Relaunch swarm
Write-Host "  Relaunching swarm for Phase 6..." -ForegroundColor Yellow
& .\swarm.ps1 -Resume -NoConfirm
