# next-swarm.ps1 - Phase Continuation Script
# Generated by Claude-4 at end of each phase to prepare the next iteration
# This is a TEMPLATE - Claude-4 should customize the banner and TASKS.md content
#
# Usage: Called automatically by supervisor when phase-complete.signal is detected
# Manual: .\next-swarm.ps1 [-NoConfirm] [-MaxPhases 999]
#
# The supervisor handles:
#   - Archiving previous phase artifacts
#   - Incrementing phase number in swarm-phase.json
# This script handles:
#   - Displaying phase transition banner
#   - Generating new TASKS.md for the next phase
#   - Launching swarm.ps1 -Resume

param(
    [switch]$NoConfirm,
    [int]$MaxPhases = 999
)

$ErrorActionPreference = "Stop"

# === READ PHASE INFO ===
$phaseFile = ".claude/swarm-phase.json"
if (Test-Path $phaseFile) {
    $phaseData = Get-Content $phaseFile | ConvertFrom-Json
    $currentPhase = [int]$phaseData.Phase
    $maxPhases = [int]$phaseData.MaxPhases
    if ($maxPhases -eq 0) { $maxPhases = $MaxPhases }
} else {
    $currentPhase = 1
    $maxPhases = $MaxPhases
}

# === READ PROJECT CONFIG ===
$configFile = ".claude/swarm-config.json"
if (Test-Path $configFile) {
    $config = Get-Content $configFile | ConvertFrom-Json
    $goal = $config.Goal
    $projectType = $config.ProjectType
    $techStack = $config.TechStack
} else {
    Write-Host "  ERROR: No swarm config found. Run swarm.ps1 first." -ForegroundColor Red
    exit 1
}

# === PHASE TRANSITION BANNER ===
Write-Host ""
Write-Host "  ============================================================" -ForegroundColor Cyan
Write-Host "         CLAUDE SWARM - Phase $currentPhase Continuation" -ForegroundColor Cyan
Write-Host "  ============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Project: $goal" -ForegroundColor White
Write-Host "  Type:    $projectType" -ForegroundColor Gray
Write-Host "  Stack:   $techStack" -ForegroundColor Gray
Write-Host "  Phase:   $currentPhase of $maxPhases" -ForegroundColor Gray
Write-Host ""

# === SHOW PREVIOUS PHASE SUMMARY ===
# Read lessons from previous phase if available
if (Test-Path "tasks/lessons.md") {
    $lessonCount = ((Get-Content "tasks/lessons.md" -Raw) | Select-String -Pattern "^### " -AllMatches).Matches.Count
    Write-Host "  Lessons captured so far: $lessonCount" -ForegroundColor Green
}

# Show signals status (dynamically discovered)
Write-Host ""
Write-Host "  Previous Phase Signals:" -ForegroundColor Yellow
$signalFiles = Get-ChildItem ".claude/signals/*.signal" -ErrorAction SilentlyContinue
if ($signalFiles) {
    foreach ($sf in $signalFiles) {
        Write-Host "    [x] $($sf.BaseName)" -ForegroundColor Green
    }
} else {
    Write-Host "    (no signals)" -ForegroundColor DarkGray
}
Write-Host ""

# === CLEAR SIGNALS FOR NEW PHASE ===
# The supervisor already does this, but clear again to be safe
Remove-Item -Path ".claude/signals/*.signal" -Force -ErrorAction SilentlyContinue
Write-Host "  Cleared signals for new phase" -ForegroundColor Gray

# === UPDATE TASKS.MD FOR NEXT PHASE ===
# NOTE: Claude-4 should customize this section when generating next-swarm.ps1
# The default behavior preserves existing TASKS.md (resume mode)
# but Claude-4 can replace this with a new TASKS.md for fresh phase work

# Check if TASKS.md needs regeneration
# Default: keep existing TASKS.md (swarm.ps1 -Resume will use it)
$regenerateTasks = $false

if ($regenerateTasks) {
    Write-Host ""
    Write-Host "  Generating new TASKS.md for Phase $currentPhase..." -ForegroundColor Yellow
    # Claude-4 should insert task generation logic here when customizing
    # Example:
    # $newTasks = @"
    # # Phase $currentPhase Tasks
    # ...
    # "@
    # $newTasks | Out-File -FilePath "tasks/TASKS.md" -Encoding UTF8
}

# === CONFIRMATION ===
if (-not $NoConfirm) {
    Write-Host ""
    $confirm = Read-Host "  Launch Phase $currentPhase? [Y/n]"
    if ($confirm -eq "n" -or $confirm -eq "N") {
        Write-Host ""
        Write-Host "  Aborted. Run .\next-swarm.ps1 when ready." -ForegroundColor Yellow
        exit 0
    }
}

# === LAUNCH SWARM ===
Write-Host ""
Write-Host "  Launching swarm for Phase $currentPhase..." -ForegroundColor Cyan
Write-Host ""

# Read agent count from config to preserve across phases
$agentCount = 4
if ($config.AgentCount) { $agentCount = [int]$config.AgentCount }

# Call swarm.ps1 with Resume to use existing config
# NoConfirm since we already confirmed above
& .\swarm.ps1 -Resume -NoConfirm -MaxPhases $maxPhases -AgentCount $agentCount
